name: algooru_flutter_assessment
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0

  #Gen
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  regexpattern: ^2.6.0


  #UI
  gap: ^3.0.1
  photo_view: ^0.14.0
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.7.0
  flutter_platform_widgets: ^6.0.2
  animated_text_kit: ^4.2.2
#  awesome_dialog: ^2.2.0
  shimmer: ^3.0.0
  #Not used usually just for the purpose of this assessment
  flutter_randomcolor: ^1.0.14
  hexcolor: ^3.0.1


  #State Management
  riverpod_annotation: ^2.3.3
  flutter_riverpod: ^2.4.9


  #used for custom external libraries not for the project's main features
  flutter_bloc: ^8.1.3

  #Api
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  #Responsive
  flutter_screenutil: ^5.9.0

  #Media
  flutter_svg: ^2.0.9
  lottie: ^3.0.0

  #Caching and Local Storage1
  path_provider: ^2.1.1
  hive: ^2.0.5
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_cache_interceptor: ^3.4.4
  get_storage: ^2.1.1
  flutter_secure_storage: ^8.1.0
  cached_network_image: ^3.3.1

  #Services
  flutter_local_notifications: ^16.3.0
  url_launcher: ^6.2.3
  easy_localization: ^3.0.3

  #Nav
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  #Gen
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.8
  #Logging
  flutter_printer: ^2.0.3


flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  assets:
    - assets/images/
    - assets/images/general/
    - assets/locales/
    - assets/fonts/
    - assets/icons/
    - assets/images/dummy/
    - assets/images/splash/
    - assets/animations/
    - env/

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/general_sans/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/general_sans/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/general_sans/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/general_sans/GeneralSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/general_sans/GeneralSans-Light.otf
          weight: 300

  uses-material-design: true